### ISSUE TITLE
Small Bug in Festival Backend on Linux

### ISSUE THREAD

**Issue by a-posadas** [ruuk/service.xbmc.tts#11]
Hello. I have a couple of comments about the festival backend and the backends in general. Please keep in mind I am new to python.

First, on linux, festival returns the list of voices separated by spaces not newlines.
So line 53:
`l = map(str.strip,d[0].rsplit('> (',1)[-1].rsplit(')',1)[0].split('\n'))`
I believe should be like this:
`l = map(str.strip,d[0].rsplit('> (',1)[-1].rsplit(')',1)[0].split())`
So it handles all white spaces.

Second, on the runCommands() function, on the off chance that the selected item has quotes, it could cause the festival command to fail. Maybe escape or remove quotes?

Finally, I'd like your thoughts on using the backends independent of the screen reader app, to say, generate wav files with kodi or to read only certain windows. Currently, someone hypothetically would have to copy the libraries and perhaps construct their own tts init class, a module for example, would reduce possible conflicts.

**Comment by ruuk** [comment]
Quite a bit late, but thanks for catching those issues.

Fixed with https://github.com/ruuk/backends/commit/84b7607498b6ff4a336681dce7d354a0540a6e19.

The backends are already their own module at https://github.com/ruuk/backends, which is also used in https://github.com/ruuk/speech.server. It seems like you are referring to creating a Kodi module that other add-ons could also use. Basically it's just not something I'm interested in maintaining, and I don't think there is enough demand to justify it. If someone starts working on something like that then I may change my mind :smile:
