### ISSUE TITLE
Speech on Mac OS X

### ISSUE THREAD

**Issue by chrisnorman7** [ruuk/service.xbmc.tts#2]
At the minute, speech on Mac OS X is really slow. Would be nice if it used something like applescript (accessible through the command "osascript"). An apple script could be constructed to use VoiceOver if it's enabled, then the say command if it's not.

I tried to find out how to make the change in the code, so I could give you a suggested fix, but I can't figure it out (damn my newness).

If you want me to try and put something together, if you could let me know where a bouts in which code the actual commands reside, then I'll give it a shot.

Cheers, and thanks for a great system!

**Comment by falcon03** [comment]
The main improvement in adding a backed for VoiceOver would be getting Braille support for free. In fact, you could configure VoiceOver to not speak with its voice for a certain application and just show the messages in Braille. I'd love this scenario...

Also, since you could configure VoiceOver to use a different audio device than the main one, Kodi Screen Reader would use that as well if leveraging it. I am not sure if we would face a performance degrade, though.

So, what do we need to move this forward?

**Comment by chrisnorman7** [comment]
Hi,
Sorry I've not been replying for ages, but I've stopped using XBMC a while back.

Instead of re-inventing the wheel, how about using accessible_output2?

hg clone http://hg.q-continuum.net/accessible_output2

After you've installed it, when you try and import it it'll complain about lack of platform_utils and platform_utils, you can get both of them from the same hg site.

To use:

from accessible_output2.outputs.auto import Auto
ao2 = Auto()

ao2.speak('This will just speak.')
ao2.braille('This will output braille if possible, raise something if not.')
ao2.output('This will try speaking and brailling, raise errors if not.')

HTH.

**Comment by ruuk** [comment]
I'm closing out this issue as it's old and has no specific issue. Feel free to open a new specific issue for anything  that still seems relavant.
