### ISSUE TITLE
extensions/adotptions: German translation, speech output device, minor bugfixes...

### ISSUE THREAD

**Issue by km-p** [ruuk/service.xbmc.tts#8]
Hi,
I've forked your projects (service.xbmc.tts & backends) and did the following:
a) added German translation.

b) added a new setting (just for eSpeak -> Pipe to aplay): set desired Speech Output Device. 
It's now possible to choose the speech output device. Output Audio to one device and Speech to a separate device. (was a requirement for my master thesis prototype).

c) minor bugfixes: 
- Screenreader for Numeric Dialog (in VirtualKeyboardReader) didn't work for me
- added a new HomeMenuReader (to get the "now playing" infos in WindowExtraInfo)
- run both util.selectSetting and util.selectPlayer in a thread (otherwise, I didn't get the Reader-Info...)

Unfortunately, I've committed all to my master-branch. But if you like, I'll create a pull request and you can checkout the things, I've done.
Maybe you'd like to pull some back...

br

**Comment by ruuk** [comment]
Sorry for the ridiculously late reply.

Much of this is in the add-on now, except perhaps for the minor bugfixes, and those may not be relevant anymore since it's going on 2 years later and much has changed in Kodi. I'm closing this issue, but feel free to point me to anything that is currently relevant or better yet, create a PR against the develop branch.
